name: Deploy Next.js to Plesk

on:
  push:
    branches:
      - main # หรือ branch ที่คุณต้องการ deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # หรือ version ที่ Next.js ของคุณใช้

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Deploy to Plesk
        env:
          HOST: ${{ secrets.PLESK_HOST }}
          USERNAME: ${{ secrets.PLESK_USERNAME }}
          PASSWORD: ${{ secrets.PLESK_PASSWORD }}
        run: |
          rsync -avz --delete -e "sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no" \
          ./out/ $USERNAME@$HOST:/categorize-test.xmmeenn.com/
